platech/Models/AddCensoredWordViewModel.cs
namespace platech.Models
{
    public class AddCensoredWordViewModel : BaseStateViewModel
    {
        public string CensoredWord { get; set; }
    }
}

platech/Models/CreateRegexViewModel.cs
using Platech.DataLayer;

namespace platech.Models
{
    public class CreateRegexViewModel : BaseStateViewModel
    {
        public string NewRegex { get; set; }
    }
}

platech/Controllers/AdminController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using platech.Helpers;
using platech.Models;
using Platech.DataLayer;

namespace platech.Controllers
{
    public class AdminController : Controller
    {
        [HttpGet]
        public IActionResult Index(State state)
        {
            var viewModel = GetViewModelForState(state);

            AddStateList(state);
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult CreateRegex(State state)
        {
            var viewModel = new CreateRegexViewModel
            {
                State = state
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateRegex(CreateRegexViewModel model)
        {
            AdminHelper.AddRegexToState(model.State, model.NewRegex);
            return RedirectToAction("Index", new { state = model.State });
        }

        [HttpGet]
        public IActionResult AddCensoredWord(State state)
        {
            var viewModel = new AddCensoredWordViewModel
            {
                State = state
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddCensoredWord(AddCensoredWordViewModel model)
        {
            AdminHelper.AddCensoredWordToState(model.State, model.CensoredWord);
            return RedirectToAction("Index", new { state = model.State });
        }

        private StatePlateManagerViewModel GetViewModelForState(State state)
        {
            var viewModel = new StatePlateManagerViewModel
            {
                State = MockDatabase.States.First(x => x.Key == state).Key,
                StateName = MockDatabase.States.First(x => x.Key == state).Value,
                CensoredWords = MockDatabase.AllStatesCensoredWords.First(x => x.Key == state).Value,
                PlateRegexs = MockDatabase.AllStatesRegexs.First(x => x.Key == state).Value
            };

            return viewModel;
        }

        private void AddStateList(State selectedState)
        {
            // State enum int as the value
            ViewBag.StateList = MockDatabase.States.Select(x => 
                new SelectListItem(x.Value, ((int)x.Key).ToString(), x.Key == selectedState));
        }
    }
}

platech/Views/Admin/AddCensoredWord.cshtml
@model platech.Models.AddCensoredWordViewModel

@{
    ViewData["Title"] = "Add Censored Word";
}

<h4>Create Censored Word for @Model.State.ToString()</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCensoredWord">
            @Html.HiddenFor(x => x.State)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CensoredWord" class="control-label"></label>
                <input asp-for="CensoredWord" class="form-control" />
                <span asp-validation-for="CensoredWord" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

platech/Views/Admin/CreateRegex.cshtml
@model platech.Models.CreateRegexViewModel

@{
    ViewData["Title"] = "Create Regex";
}

<h4>Create Regex for @Model.State.ToString()</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRegex">
            @Html.HiddenFor(x => x.State)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NewRegex" class="control-label"></label>
                <input asp-for="NewRegex" class="form-control" />
                <span asp-validation-for="NewRegex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

platech/Views/Admin/Index.cshtml
@model StatePlateManagerViewModel
@{
    ViewData["Title"] = "State Plate Manager";
}

<h2>State Manager</h2>

<div>
    <h4>State Manager View</h4>
    <hr />

    @*@Html.DisplayFor(x => x.State)*@
    @Html.DropDownListFor(m => m.State, (IEnumerable<SelectListItem>)ViewBag.StateList, "State Options", new { @id = "stateDropdown" })

    <hr />
    <h4>Plate Regular Expressions</h4>
    <table id="regexTable" class="table table-bordered">
        
        @foreach (var regex in Model.PlateRegexs)
        {
            <tr>
                <td>@regex</td>
            </tr>
        }
    </table>
    @Html.ActionLink("Create New Regular Expression", "CreateRegex", new { state = (int)Model.State })

    <hr />
    <h4>Censored words</h4>
    <table id="censoredTable" class="table table-bordered">
        
        @foreach (var censoredWord in Model.CensoredWords)
        {
            <tr>
                <td>@censoredWord</td>
            </tr>
        }
    </table>
    @Html.ActionLink("Add New", "AddCensoredWord", new { state = (int)Model.State })
</div>

<script>
    window.onload = function () {
        $('#stateDropdown').change(function () {
            var stateId = $('#stateDropdown').val();
            var action = '@Url.Action("Index", "Admin")';
            window.location.replace(action + '?state=' + stateId);
        });
    }
</script>